### ISSUE TITLE
Debugging non-editor processes

### ISSUE THREAD

**Issue by nagaohiroki** [nagaohiroki/unity.nvim#1]

**Comment by nagaohiroki** [comment]
The EndPoint of a pre-built Unity application can be output from the command prompt, but cannot be detected using vim.system.


``` lua
	local system_obj = vim.system({ 'dotnet', 'UnityAttachProbe.dll' }, { text = true })
	local probe_result = system_obj:wait().stdout
	vim.print(probe_result)
```

**Comment by prashanthsp6498** [comment]
Hi @nagaohiroki 
This is really nice feature https://github.com/nagaohiroki/unity.nvim/commit/f13e69c435eb7d8e6fc7df3a7f02e23259cc2478 but `projectName` will be blank which makes it difficult to choose which process to attach.
It would be better if `processId` is added along with `projectName` here https://github.com/nagaohiroki/unity.nvim/commit/f13e69c435eb7d8e6fc7df3a7f02e23259cc2478#diff-3286b7bf13e2a85448565a5072b4edfca5ba1b57443868a7cfe8b2e980d2ec7fR177 , because if `projectName` is blank then we'll have `processId` to decide.

In my case `projectName` is blank( I don't know from where this data will be fetched)
![image](https://github.com/user-attachments/assets/2a000f63-4690-4be9-9f72-a6b257537f55)

**Comment by nagaohiroki** [comment]
@prashanthsp6498 
Thank you.
I didn't anticipate the case where `projectName` would be blank. I'll add `processId`.

**Comment by nagaohiroki** [comment]
@prashanthsp6498 
https://github.com/nagaohiroki/unity.nvim/commit/229a2da36dc4430469456ec8c01cad26bd20d70a

Added `processId` to process selection.
Also added `packageName` because processId for Windows Player can be 0.
UnityAttachProbe information can be viewed with neovim's `:ShowUnityProcess` command.

**Comment by prashanthsp6498** [comment]
Thank you @nagaohiroki, I have tested the changes for editor instance, it is working fine.
